config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :friends
  root 'home#index'
  get 'home/about'
  get "search" => "friends#search"
  resources :invites, only: [:create]
  resources :notifications, only: [:index]
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 

  
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    validates_presence_of :email, :first_name , class: :friend
    validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create
end

app/models/invite.rb
class Invite < ApplicationRecord
    STATUS_TYPES = {"pending" => 1, "accepted" => 2, "rejected" => 3}.freeze
    enum status: STATUS_TYPES

    validates :inviter_id, uniqueness: { scope: :invitee_id, message: "invite already sent" }

    belongs_to :user, class_name: "User", foreign_key: "inviter_id"
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends   
  has_many :invites, class_name: "Invite", foreign_key: "inviter_id"
  has_many :notifications, class_name: "Invite", foreign_key: "invitee_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :update]
  before_action :authenticate_user!, only: [:index, :search]
  # GET /friends or /friends.json
  def index
    
    @friends = current_user.friends
    
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
  def search
    
    @friends = current_user.friends.where(first_name: keyword)
    #@friends = Friend.where(first_name: keyword, user_id: current_user.id) another way could be used.
    render "index"
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
      redirect_to freinds_path, notice:"not authorized to edit this friend " if @friend.nil?
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter,:user_id)
    end

    def keyword
      params[:keyword].strip
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! , only: [:index]

  def index
    @users = User.all.where.not(id: current_user.id)
  end

  def about
    
  end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
    before_action :authenticate_user! , only: [:create]
  
    def create
      invite = Invite.new
      invite.inviter_id = current_user.id
      invite.invitee_id = params["invitee_id"]
      invite.status = 1
      invite.save!

      redirect_to root_path
    end
  
    
  
  end
  

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_action :authenticate_user! , only: [:index]
  
    def index
      @notifications= current_user.notifications.where(status: 1)
    end
  
    
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name", required: true %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, class:"form-control", placeholder:"Email", required: true %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %> 
  
    <%= form.submit %>
  </div>
<% end %>
  

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>
<% if action_name == "search" %>
<h1>Search Results for: <%= params[:keyword].strip %> </h1>
<% else%>
<h1>Friends List</h1>
<% end %>


<table class="table" >
  <thead class="thead-dark">
    <tr>
      <th>First Name</th>
      <th>Last Name </th>
      <th>Email </th>
      <th>phone</th>
      <th>Twitter</th>
      <th> User ID</th>
      <th colspan ="2"> 
      
    </tr>
  </thead>
  <tbody>
   
  <% @friends.each do |friend| %>
  <tr> 
    <td><%= friend.first_name %></td>
    <td><%= friend.last_name %></td>
    <td><%= friend.email %></td>
    <td><%= friend.phone %></td>
    <td><%= friend.twitter %></td>
    <td> <%= friend.user_id %> </td>
    <td><%= link_to "Show this friend", friend %></td>
    
    <td><%= link_to "Edit this friend", edit_friend_path(friend) %></td>
    <td><%= link_to "Destroy", friend, methode: :delete, data: { confirm: 'Are You sure!?'} %></td>
    
  </tr> 
    <%end%>
 
  </tbody>
</table> 
<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-secondary" %> |
  <%= link_to "Back to friends", friends_path , class:"btn btn-secondary"%>
<br/>
<br/>

  <%= button_to "Destroy this friend", @friend, method: :delete, class:"btn btn-danger"  %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiar navbary navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App", root_path, class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
          
        </li>
        
        
        <% if user_signed_in? %>
          <li>
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %>
        </li>

        <li>
        <%= link_to " Edit Profile ", edit_user_registration_path, class:"nav-link" %>
        </li>
        
        <li>
        <%= link_to " Add a Friend ", new_friend_path, class:"nav-link" %>
        </li>
        <li>
        <%= link_to " Notifications ", notifications_path, class:"nav-link" %>
        </li>
        <li>
        <%= link_to "Friends List ", friends_path, class:"nav-link" %>
        </li>
      <%= form_with url: "/search", html: {class: "d-flex" }, method: :get do |form| %>
        <%= form.text_field :keyword, class: "form-control me-2"  %>
        <%= form.submit "Search", class: "btn btn-outline-success" %>
      <% end %>
        <% else %>
      <li>
      <%= link_to " Sign Up ", new_user_registration_path, class:"nav-link" %>
      </li>
      <li>
      <%= link_to " Sign in ", new_user_session_path, class:"nav-link" %>
      </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us </h1>

app/views/home/index.html.erb
<h1>All Users</h1>

<table class="table" >
  <thead class="thead-dark">
    <tr>
      <th>Email</th>
      <th>Invite Status</th>
    </tr>
  </thead>
  <tbody>
   
  <% @users.each do |user| %>
  <tr> 
    <td><%= user.email %></td>
    
    <td><%= current_user.invites.where(invitee_id: user.id).last&.status %></td>
    <% unless current_user.invites.where(invitee_id: user.id).exists? %>
    <td><%= button_to " send invite ", invites_path , method: :post, params: { invitee_id: user.id }, class:"nav-link" %></td>
    <% end%>    
    </tr> 

    
    <%end%>
 
  </tbody>
</table> 

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en" dir="lfl">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">

    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header"%>
    <br/>
    <br/>
    <div class="container">
    <%= yield %>
    
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/notifications/index.html.erb
<h1>All Notification</h1>

<table class="table" >
  <thead class="thead-dark">
    <tr>
      <th>Email</th>
      <th> Actions </th>
    </tr>
  </thead>
  <tbody>
   
  <% @notifications.each do |noti| %>
  <tr> 
    <td><%= noti.user.email %></td>
    <td> dddddddd</td>
    </tr> 

    
    <%end%>
 
  </tbody>
</table> 